on:
  push:
    branches: [master]

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Generate deployment package
      run: zip -r deploy.zip * -x "**node_modules**" && cd target/ && ls
    
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'

#     - name: Beanstalk Deploy
#       uses: einaregilsson/beanstalk-deploy@v10
#       with:
#         aws_access_key:  asd
#         aws_secret_key: asd
#         region: as
#         application_name: asd
#         environment_name: user-service
#         version_label: 
